version: "{build}"

branches:
  only:
    - release-branch.go1.7
    - release-branch.go1.8
    - master

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - mkdir c:\gopath
  - go get github.com/mikioh/ipaddr

build_script:
  - go test -v -race
  - go test -v -run=none -bench=. -benchmem
